baseURL = "https://christian0919.github.io/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
rssLimit = 10
theme = "hugo-texify3"
title = "Init0"

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="Init0"
author = "Christian Lopez"
description = "personal blog"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

  [params.commentEngine]
  code = """
  <script src="https://giscus.app/client.js"
        data-repo="michaelneuper/website"
        data-repo-id="R_kgDOIjPNaQ"
        data-category="General"
        data-category-id="DIC_kwDOIjPNac4CaklA"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme=""
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
  </script>
  """

  [params.buymeacoffee]
  code = """
  <script async data-name="" 
        data-cfasync="false" 
        src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
        data-id="" 
        data-description="Like what I do? Buy me a coffee!" 
        data-message="" 
        data-color="#d79921" 
        data-position="Right" 
        data-x_margin="18" 
        data-y_margin="18"
        crossorigin="anonymous">
  </script>
  """

  [params.sharingbuttons]
  facebook = true
  twitter = true
  email = false
  linkedin = true
  reddit = false
  whatsapp = false
  hackernews = false
  telegram = true
